version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx.loc.crt:/etc/nginx/nginx.loc.crt'
      - './nginx.loc.key:/etc/nginx/nginx.loc.key'
    ports:
      - '10443:443'
